name: iOS - Deploy Staging build to TestFlight
on:
  # Trigger the workflow on push action
  push:
    branches:
      - develop

jobs:
  build_and_upload_to_testflight:
    name: Build And Upload iOS Application To TestFlight
    runs-on: macOS-latest
    env:
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      APPSTORE_CONNECT_API_KEY: ${{ secrets.APPSTORE_CONNECT_API_KEY }}
    steps:
    - uses: actions/checkout@v1

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Setup Flutter environment
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        flutter-version: '3.7.7'

    - name: Get flutter dependencies
      run: flutter pub get

    - name: Run code generator
      run: flutter packages pub run build_runner build --delete-conflicting-outputs

    - name: Bundle install
      run: cd ./ios && bundle install

    - name: Pod install
      run: cd ./ios && bundle exec pod install

    - name: Match AppStore
      run: cd ./ios && bundle exec fastlane sync_appstore_staging_signing

    - name: Deploy to TestFlight
      run: |
        cd ./ios && bundle exec fastlane build_and_upload_testflight_staging_app
